<<<<<<< HEAD
spring.application.name=notificaciones
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

=======
>>>>>>> 0ce737d3fdd4d17416de0646b83f3901e9f1a661
server.port=8087
spring.datasource.url=jdbc:mysql://localhost:3306/bd_notificaciones
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
<<<<<<< HEAD

# Email configuration (SMTP)
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
=======
spring.application.name=notificaciones
>>>>>>> 0ce737d3fdd4d17416de0646b83f3901e9f1a661
